module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'module-resolver',
      {
        cwd: 'babelrc',
        root: ['./src'],
        extensions: ['.js', '.ios.js', '.android.js'],
        alias: {
          assets: './src/assets',
          'components/elements': './src/components/elements',
          'components/widgets': './src/components/widgets',
          'components/layouts': './src/components/layouts',
          'screens/generic': './src/screens/generic',
          'screens/sales': './src/screens/sales',
          'screens/tourPlan': './src/screens/tour-plan',
          'screens/directory': './src/screens/directory',
          'screens/home': './src/screens/home',
          'screens/settings': './src/screens/settings',
          screens: './src/screens',
          navigations: './src/navigations',
          services: './src/services',
          themes: './src/themes',
          utils: './src/utils',
          common: './src/common',
          database: './src/database',
          helper: './src/helper',
          reducers: './src/store/reducers',
          sagas: './src/store/sagas',
          selectors: './src/store/selectors',
          states: './src/store/states',
          locale: './src/locale',
          'screen/eDetailing': './src/screens/directory/e-detailing',
        },
      },
    ],
  ],
};
