apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: supermandev.azurecr.io/frontend:#{Build.BuildId}#
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-ingress
  annotations:
    #kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/use-regex: "true"
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  tls:
  - hosts:
    - services-all.0a6418a61f9c4aeb86ee.centralindia.aksapp.io
    secretName: service-ingress-tls
  rules:
  - host: services-all.0a6418a61f9c4aeb86ee.centralindia.aksapp.io
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
              
      - path: /.*
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
     
      
                       