// SCHEMA NAMES
export const MASTER_TABLES_DOWNLOAD_STATUS = 'MASTER_TABLES_DOWNLOAD_STATUS';
// TABLE NAMES
export const MASTER_TABLE_PARTY = 'MASTER_TABLE_PARTY';
export const MASTER_TABLE_PARTY_API = 'MASTER_TABLE_PARTY_API';
