export {default as Label} from './Label';
export {LabelVariant} from './Label';
export {default as Button} from './Button';
export {default as Area} from './AreaChip';
export {default as DoctorDetailsWrapper} from './DoctorDetailsWrapper';
export {default as DoctorDetails} from './DoctorDetails';
export {default as Frequency} from './Frequency';
export {default as Modal} from './Modal';
export {default as Dropdown} from './Dropdown';
export {default as Border} from './Border';
