const Strings = {
  heading: 'Welcome',
  forgotpwd: 'Forgot password',
  week: ['week 1', 'week 2', 'week 3', 'week 4'],
  selectDoctorAndChemist: 'Select doctors and chemist',
  selectArea: 'Select Area',
  selectVisit: 'Select Visit',
  planCompliance: 'Plan Compliance',
  viewTourPlan: 'View Tour Plan for',
  dailyPlan: 'Daily Plan',
  tourPlan: 'Tour Plan',
  login: 'Login',
  myPlan: 'My Plan',
  stp: 'Standard Tour Plan(STP)',
  today: 'Today',
  patchName: 'Patch Name',
  selectPatch: 'Select Patch',
  close: 'Close',
  done: 'Done',
  saveDraft: 'Save Draft',
  youHave: 'You have',
  numberOfDoctors: '11 doctors',
  and: 'and',
  numberOfChemist: '6 chemist',
  visits: 'visits',
  reviewDCR: 'Review DCR',
  addToTodayPlan: "Add to Today's Plan",
};

export default Strings;
