const Strings = {
  superman: 'superman',
  heading: 'Welcome',
  forgotpwd: 'Forgot password',
  week: [1, 2, 3, 4],
  weekText: 'Week',
  selectDoctorAndChemist: 'Select doctors and chemists',
  selectArea: 'Select Area',
  selectVisit: 'Selected Visits',
  planCompliance: 'Plan Compliance',
  viewTourPlan: 'View Tour Plan for',
  dailyPlan: 'Daily Plan',
  tourPlan: 'Tour Plan',
  login: 'Access using OneLogin',
  myPlan: 'My Plan',
  stpWithAbbreviation: 'Standard Tour Plan(STP)',
  stp: 'Standard Tour Plan',
  today: 'Today',
  patchName: 'Patch Name',
  selectPatch: 'Select Patch',
  close: 'Close',
  done: 'Done',
  saveDraft: 'Save Draft',
  youHave: 'You have',
  numberOfDoctors: 'doctor',
  and: 'and',
  numberOfChemist: 'chemist',
  visits: 'visits',
  reviewDCR: 'Review DCR',
  addToTodayPlan: "Add to Today's Plan",
  Legends: {
    kycDoctor: 'KYC Doctors',
    visitSchedule: 'High number of visits scheduled',
    events: 'Events',
    leave: 'Leave',
    today: 'Today',
    holiday: 'Holiday',
    location: 'Location',
    complainceNotMet: 'Compliance not met',
    exStation: 'Ex-station',
    exStationTitle: '(Ex)',
  },
  kyc: 'KYC',
  all: 'All',
  downloadingContent: 'Downloading content from server to your device',
  downloadingMaster: 'Downloading performance master',
  error: 'Error',
  info: 'Info',
  logOffmsg: 'Are you sure you want to Log off?',
  cancel: 'Cancel',
  ok: 'OK',
  doctorUniverse: 'Doctor Universe',
  addOtherDoctors: 'Add other doctors',
  labelRssdi: 'RSSDI',
  dailyPlanTileTitle: 'Samples requested – Telmikind',
  removeDoctorConfirmation: 'Do you want to remove this doctor visit?',
  proceed: 'Proceed',
  removeFromToday: 'Remove from today',
  doctorProfileTab: {
    prepSheet: 'Prep Sheet',
    doctor360: 'Doctor 360',
    performance: 'Performance',
    contentStudio: 'Content Studio',
    engagement: 'Engagement',
    tasks: 'Tasks',
    surveys: 'Surveys',
  },
  doctorProfile: 'Doctor Profile',
  priorityProductCard: {
    header: 'Priority Products',
    amlokindAt: 'Amlokind AT',
    two: '2',
    p1: 'P1',
    p2: 'P2',
    description: 'Detailed on ',
    progressNumber: '45',
    slashNumber: '/80',
    secondProgressbar: '45',
    slashSecondNumber: '/120',
    neurokind: 'Neurokind',
    nine: '9%',
    ten: '10%',
    tabDes: 'MANKIND/TOTAL QUANTITY',
    foc: 'FOC',
    gx: '(Gx)',
    sow: '(SOW)',
    conductRcpa: 'Conduct RCPA',
    na: 'NA',
  },
  captureDcr: 'Capture DCR',
  startEdetail: 'Start eDetailing',
  detail: 'detail',
  removed: 'Removed',
  removedDoctor: "You have removed a doctor from today's visit",
  undo: 'UNDO',
  createNewStp: 'Create a new STP',
  patchAlreadyExists: '*The patch name entered already exist',
  already30PatchesCreated: '*Already 30 patches created',
  somethingWentWrong: 'Something went wrong. Please try again!',
  confirmation: 'Confirmation',
  patchUsedForOtherWeekDay:
    'This patch is used for other Weekdays. Do you want to make changes in all the days?',
  yes: 'Yes',
  no: 'No',
  tillDate: 'Till Date',
  comingSoon: 'Coming soon ***',
  moreActions: 'More Actions',
  beginRCPA: 'Begin RCPA',
  eDetailing: 'eDetailing',
  startPresentation: 'Start Presentation',
  priorityProducts: 'Priority Products',
  otherProducts: 'Other Products',
  doctorDetail: {
    openTasks: {
      openTask: 'Open Tasks',
      viewAll: 'View All',
      viewLess: 'View Less',
      due: 'DUE',
    },
    dcr: {
      what: 'What',
      kindOfVisit: 'kind of visit',
      wasIt: 'was it?',
      regVisit: 'Regular Visit',
      justMe: 'Just Me',
      jointVisit: 'Joint Visit',
      posts: 'FLM/SLM/TLM',
      addDoctor: 'ADD A DOCTOR',
      btnDone: 'Done',
      feedback: 'Feedback',
    },
  },
  dr: 'Dr.',
  success: 'Success',
  patchSaved: 'Patch successfully saved',
  noRecordsForSelection: 'No records for current selection',
  errorRemovingParty: 'There is some error removing the party',
  errorFetchingParties: 'There is some error fetching parties',
  exitConfirmation: 'Are you sure you want to exit Superman?',
  patchSaveForPrevDay: 'Patch for previous day(s) has been saved',
  noPatchFound: 'No patch found',
  congratulations: 'Congratulations!',
  takeMeToHome: 'Take me to Home',
  beginJourney: "Let's begin your journey",
  successfullyCreatedSTP: 'You have successfully created a Standard Tour Plan',
  errorFetchingComplianceRules: 'There is some error in fetching rules',
  tourPlanRules: 'tour plan rules',
  exStation: 'Ex',
  patchExhaustedForParty:
    'One or more doctors added in the patch do not have further visiting slots, do you want to create a new patch.',
  directory: {
    tab: {
      doctors: 'Doctors',
      chemists: 'Chemists',
      stocklists: 'Stocklists',
    },
    listHeader: {
      doctor: 'DOCTOR',
      speciality: 'SPECIALITY',
      region: 'REGION',
    },
    noResult: 'No Records found',
    btns: {
      addTodayPlan: "Add to Today's Plan",
      startEdetail: 'eDetail',
    },
    docAddedTodayPlan: 'Doctor added successfully',
  },
  setting: {
    tab: {
      conflicts: 'Conflict',
    },
  },
  searchBar: {
    errors: {
      validName: 'Please Enter Valid name',
      partyName: 'Please Enter Party Name',
      minChar: 'Please Enter atleast 2 characters',
    },
    toastBtns: {
      clear: 'Clear',
      continue: 'Continue',
    },
    searchPlaceholder: 'Search Doctors Here',
  },
  areaSelectionConfirmation:
    'The selections done by you will be lost. Do you want to proceed?',
  warning: 'Warning',
  monthlyActions: {
    save: 'Save',
    submitSTP: 'Submit STP',
  },
  frquecySlotExhausted:
    'Frequency slots for few doctors has been exhausted, a new patch name has been created',
  selectDocToCreatePatch: 'Please select any doctor to create a patch.',
  backgroundTask: {
    lastSync: 'Last Synced:',
    lastModifiedTime: 'Last Modified On',
    conflictMessage: 'Conflict Message',
    errorMessage: 'Error Message',
    useDevice: 'Use Device',
    useServer: 'Use Server',
    toastBtns: {
      message: 'Sync Status',
      viewSummary: 'View Summary',
      syncInitiatedMessage: 'Sync request has been initiated.',
      successMessage: 'Requested sync has been completed successfully.',
      conflictMessage: 'Sync activity was completed with a conflict.',
      failureMessage: 'Sync activity could not be completed.',
      alreadRunningMessage: 'Sync activity is already in progress.',
    },
  },
  noInternet: 'No Internet',
  checkInternet: 'Check you internet connection',
};

export default Strings;
