const Strings = {
  superman: 'superman',
  heading: 'Welcome',
  forgotpwd: 'Forgot password',
  week: ['week 1', 'week 2', 'week 3', 'week 4'],
  selectDoctorAndChemist: 'Select doctors and chemist',
  selectArea: 'Select Area',
  selectVisit: 'Selected Visits',
  planCompliance: 'Plan Compliance',
  viewTourPlan: 'View Tour Plan for',
  dailyPlan: 'Daily Plan',
  tourPlan: 'Tour Plan',
  login: 'Access using OneLogin',
  myPlan: 'My Plan',
  stpWithAbbreviation: 'Standard Tour Plan(STP)',
  stp: 'Standard Tour Plan',
  today: 'Today',
  patchName: 'Patch Name',
  selectPatch: 'Select Patch',
  close: 'Close',
  done: 'Done',
  saveDraft: 'Save Draft',
  youHave: 'You have',
  numberOfDoctors: '5 doctors',
  and: 'and',
  numberOfChemist: '1 chemist',
  visits: 'visits',
  reviewDCR: 'Review DCR',
  addToTodayPlan: "Add to Today's Plan",
  Legends: {
    kycDoctor: 'KYC Doctors',
    visitSchedule: 'High number of visits scheduled',
    events: 'Events',
    leave: 'Leave',
    today: 'Today',
    holiday: 'Holiday',
  },
  kyc: 'KYC',
  all: 'All',
  downloadingContent: 'Downloading content from server to your device',
  downloadingMaster: 'Downloading performance master',
  error: 'Error',
  info: 'Info',
  logOffmsg: 'Are you sure you want to Log off?',
  cancel: 'Cancel',
  ok: 'OK',
  doctorUniverse: 'Doctor Universe',
  addOtherDoctors: 'Add other doctors',
  labelRssdi: 'RSSDI',
  dailyPlanTileTitle: 'Samples requested – Telmikind',
  removeDoctorConfirmation: 'Do you want to remove this doctor visit?',
  proceed: 'Proceed',
  removeFromToday: 'Remove from today',
  doctorProfileTab: {
    prepSheet: 'Prep Sheet',
    doctor360: 'Doctor 360',
    performance: 'Performance',
    contentStudio: 'Content Studio',
    engagement: 'Engagement',
    tasks: 'Tasks',
    surveys: 'Surveys',
  },
  doctorProfile: 'Doctor Profile',
  priorityProductCard: {
    header: 'Priority Products',
    amlokindAt: 'Amlokind AT',
    one: '1',
    p1: 'p1',
    description: 'Detailed on 3 March, 2021',
    progressNumber: '45/80',
    nine: '9%',
    tabDes: 'Mankind’s Prescription/TOtal prescription',
  },
  captureDcr: 'Capture DCR',
  startEdetail: 'Start eDetailing',
  detail: 'detail',
  removed: 'Removed',
  removedDoctor: "You have removed a doctor from today's visit",
  undo: 'UNDO',
  createNewStp: 'Create a new STP',
  patchAlreadyExists: '*The patch name entered already exist',
  already30PatchesCreated: '*Already 30 patches created',
  somethingWentWrong: 'Something went wrong. Please try again!',
  confirmation: 'Confirmation',
  patchUsedForOtherWeekDay:
    'This patch is used for other Week>days. Do you want to make changes in all the days?',
  yes: 'Yes',
  no: 'No',
  tillDate: 'Till Date',
  comingSoon: 'Coming soon ***',
  moreActions: 'More Actions',
  beginRCPA: 'Begin RCPA',
};

export default Strings;
